[playerConfig]

[playerConfig.claims]
bonusChunkForceloads = 0
color = 16371200
usedSub = "default"
usedServerSub = "default"
name = ""
bonusChunkClaims = 0
protectClaimedChunks = false

[playerConfig.claims.protection]
netherPortalsPlayers = 0
projectileHitHostileSpawn = 0
pistonBarrier = false
spawnersHostile = false
entitiesFromPlayers = 0
netherPortalsMobs = 0
itemPickupPlayers = 0
playersFromMobs = false
fromAllyParties = false
entitiesRedirect = false
neighborChunksItemUse = false
itemPickupMobs = 0
tripwireFromOther = 0
entitiesFromExplosions = false
itemTossRedirect = false
playerLightning = 0
entitiesFromMobs = 0
playersFromPlayers = false
platesFromOther = 0
blocksFromOther = 0
dispenserBarrier = false
entitiesFromOther = 0
netherPortalsOther = 0
naturalSpawnHostile = false
fromParty = false
blocksRedirect = false
projectileHitFriendlySpawn = 0
mobLoot = 0
overrideMobGriefingRule = false
fluidBarrier = false
tripwireFromPlayers = 0
cropTrample = false
blocksFromExplosions = false
playersFromOther = false
tripwireFromMobs = 0
chorusFruitTeleport = 0
buttonsFromProjectiles = 0
xpPickup = 0
itemUse = 0
spawnersFriendly = false
platesFromPlayers = 0
entitiesFromFire = false
raids = false
itemPickupRedirect = false
blocksFromMobs = 0
playersRedirect = false
targetsFromProjectiles = 0
blocksFromPlayers = 0
itemTossPlayers = 0
platesFromMobs = 0
fromFrostWalking = 0
itemTossMobs = 0
itemTossOther = 0
playerDeathLoot = 0
naturalSpawnFriendly = false
fromFireSpread = false

			[playerConfig.claims.protection.exceptionGroups]

				[playerConfig.claims.protection.exceptionGroups.block]

					[playerConfig.claims.protection.exceptionGroups.block.break]
						Everything = 3
						Crops = 3

					[playerConfig.claims.protection.exceptionGroups.block.anyItemInteract]
						Everything = 3

					[playerConfig.claims.protection.exceptionGroups.block.interact]
						Redstone_Components = 3
						Containers = 3
						Anvil = 3

				[playerConfig.claims.protection.exceptionGroups.entity]

					[playerConfig.claims.protection.exceptionGroups.entity.anyItemInteract]
						Armor_Stand = 3
						Item_Frames = 3

					[playerConfig.claims.protection.exceptionGroups.entity.interact]
						Villager = 3

					[playerConfig.claims.protection.exceptionGroups.entity.entityAccess]
						Zombies = 3

		[playerConfig.claims.forceload]
			offlineForceload = false
			enabled = false

	[playerConfig.parties]
		shareLocationWithParty = false
		shareLocationWithMutualAllyParties = false
		name = "DISABLED"
		receiveLocationsFromMutualAllyParties = false
		receiveLocationsFromParty = false

